// <auto-generated />
namespace AngularTutorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_sprint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_sprint));
        
        string IMigrationMetadata.Id
        {
            get { return "201606261436029_add_sprint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
